"""Perception Blackboard models for gameplay AI systems.

This module houses the read-only perception snapshots generated by the engine's
spatial hashing and stats tracking systems, which are passed to the AI brain
for decision making.
"""

from dataclasses import dataclass


@dataclass(slots=True)
class TargetInfo:
    """Perception snapshot of a single visible entity in the spatial hash.

    Attributes:
        entity_id: The runtime ID of the target entity.
        stable_id: The persistent stable ID of the target entity.
        type_id: The species or object type identifier (e.g. 'reimu').
        growth_stage: The current growth stage (e.g. 'Baby', 'Adult').
        x: The target's X position in the world space.
        y: The target's Y position in the world space.
        distance: The distance from the perceiving entity to this target.
        affinity: The social affinity score between the entities (-100 to 100).
        is_threat: Whether the target is perceived as a predator or threat.
        is_prey: Whether the target is perceived as food/prey.
        is_family: Whether the target shares a family association.
        tags: The set of tags attached to the target entity (e.g. {'Food'}).
    """

    entity_id: int
    stable_id: int
    type_id: str
    growth_stage: str
    x: float
    y: float
    distance: float
    affinity: float
    is_threat: bool
    is_prey: bool
    is_family: bool
    tags: set[str]


@dataclass(slots=True)
class Blackboard:
    """Localized perception snapshot passed to the Yukkuri behavior logic.

    Attributes:
        entity_id: The runtime ID of the perceiving entity.
        stats: Dictionary mapping stat names (hunger, energy, etc.) to values.
        x: Current X position of the perceiving entity.
        y: Current Y position of the perceiving entity.
        altitude: Current flight altitude.
        flight_state: Numerical representation of the current flight state.
        visible_targets: List of TargetInfo objects representing perceived targets.
        current_action: Name of the currently executing action or behavior.
        short_term_memory: Maps entity_id to tuple of (x, y, timestamp) of
            last-known target coordinates.
    """

    entity_id: int
    stats: dict[str, float]
    x: float
    y: float
    altitude: float
    flight_state: int
    visible_targets: list[TargetInfo]
    current_action: str
    short_term_memory: dict[int, tuple[float, float, float]]
