"""AI Commands and CommandQueue module.

This module houses the high-level commands generated by Python gameplay
systems to request physical engine changes, along with a thread-safe or
system-wide queue to collect and dispatch them.
"""

from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Any


class CommandType(Enum):
    """Enumeration of high-level gameplay action command types."""

    MOVE_TO = auto()
    FLEE = auto()
    SPEAK = auto()
    PLAY_ANIMATION = auto()
    ATTACK = auto()
    INTERACT = auto()
    MODIFY_STAT = auto()


@dataclass(slots=True)
class Command:
    """A high-level command request to be dispatched and executed by the engine.

    Attributes:
        type: The specific CommandType category.
        entity_id: The runtime ID of the target entity to apply the command to.
        payload: Dictionary containing arguments tailored for the command type.
    """

    type: CommandType
    entity_id: int
    payload: dict[str, Any] = field(default_factory=dict)


class CommandQueue:
    """Queue of gameplay action commands published during a frame's AI tick."""

    def __init__(self) -> None:
        """Initializes an empty command queue."""
        self._commands: list[Command] = []

    def push(self, command: Command) -> None:
        """Appends a new command to the execution queue.

        Args:
            command: The Command instance to queue.
        """
        self._commands.append(command)

    def pop_all(self) -> list[Command]:
        """Retrieves and clears all queued commands for the current frame.

        Returns:
            list[Command]: The list of queued commands.
        """
        commands = list(self._commands)
        self._commands.clear()
        return commands

    def clear(self) -> None:
        """Clears all pending commands in the queue."""
        self._commands.clear()
