"""Motor Dispatcher System Module.

Converts high-level AI commands generated by Python gameplay systems
into direct ECS component mutations for physics and rendering execution.
"""

from typing import Any
from loguru import logger
import pymunk

from ...engine.ecs import System, World
from ..ai.commands import CommandQueue, CommandType
from ..components import (
    MoveCommand,
    Needs,
    InteractionRequest,
)
from ...engine.components import (
    MovementController,
    Animator,
    Sprite,
    Transform,
)
from ..prefabs.effects import create_floating_text


class MotorDispatcher(System):
    """ECS system that dispatches high-level AI commands.

    Processes CommandQueue packets published during the frame AI updates and
    applies physical and rendering changes to entities.
    """

    run_after = ["BehaviorSystem"]
    run_before = ["SteeringSystem"]

    def update(self, world: World, dt: float) -> None:
        """Processes and applies all queued commands from the current frame.

        Args:
            world: The ECS World.
            dt: Delta time.
        """
        command_queue = world.services.try_get(CommandQueue)
        if not command_queue:
            return

        for cmd in command_queue.pop_all():
            entity_id = cmd.entity_id
            if not world.entity_exists(entity_id):
                continue

            try:
                self._dispatch_command(world, cmd)
            except Exception as e:
                logger.error(
                    "Failed to dispatch command {} for entity {}: {}",
                    cmd.type,
                    entity_id,
                    e,
                )

    def _dispatch_command(self, world: World, cmd: Any) -> None:
        """Executes a single command packet against the world state."""
        entity_id = cmd.entity_id

        if cmd.type == CommandType.MOVE_TO:
            # High-level MOVE_TO commands are processed physically by the existing
            # NavigationController (called by the behavior actions) to maintain 100%
            # backward compatibility in Pygame and avoid steering/pathfinding conflicts.
            pass

        elif cmd.type == CommandType.FLEE:
            vx = cmd.payload.get("velocity_x", 0.0)
            vy = cmd.payload.get("velocity_y", 0.0)

            controller = world.try_get_component(entity_id, MovementController)
            if controller:
                controller.target_velocity = pymunk.Vec2d(vx, vy)

            if world.has_component(entity_id, MoveCommand):
                world.commands.remove_component(entity_id, MoveCommand)

        elif cmd.type == CommandType.SPEAK:
            text = cmd.payload.get("text", "")
            color = cmd.payload.get("color", (255, 255, 255))
            lifetime = cmd.payload.get("lifetime", 2.0)

            transform = world.try_get_component(entity_id, Transform)
            if transform:
                create_floating_text(
                    world,
                    x=transform.x,
                    y=transform.y - 20,
                    text=text,
                    color=color,
                    lifetime=lifetime,
                    velocity_y=-30.0,
                )

        elif cmd.type == CommandType.PLAY_ANIMATION:
            anim_name = cmd.payload.get("animation_name", "default")

            animator = world.try_get_component(entity_id, Animator)
            if animator:
                animator.current_animation = anim_name
            else:
                sprite = world.try_get_component(entity_id, Sprite)
                if sprite:
                    sprite.image_name = anim_name

        elif cmd.type == CommandType.INTERACT:
            target_id = cmd.payload.get("target_id", None)
            if target_id is not None:
                req = InteractionRequest(
                    target_id=target_id,
                    consume=cmd.payload.get("consume", True),
                    action=cmd.payload.get("action", "DEFAULT"),
                )
                world.commands.add_component(entity_id, req)

        elif cmd.type == CommandType.MODIFY_STAT:
            stat_name = cmd.payload.get("stat_name", "")
            amount = cmd.payload.get("amount", 0.0)

            needs = world.try_get_component(entity_id, Needs)
            if needs and hasattr(needs, stat_name):
                current_val = getattr(needs, stat_name)
                setattr(needs, stat_name, current_val + amount)
